In [12]:
#Import libraries

import pandas as pd
import numpy as np
import os

In [13]:
path = r'C:\Users\Timbr\OneDrive\Desktop\Career Foundry\Data Immersion\Achievement 6'

In [14]:
#import 'NHL_Data_2008-2022_kaggle.csv' to make df_kaggle
df_kaggle = pd.read_csv(os.path.join(path, 'Data', 'Original Data', 'NHL_Data_2008-2022_kaggle.csv'), index_col = False)

In [15]:
#import 'NHL_Data_2008-2022_Nat_Stat_Trick.csv' to make df_Nat_Stat_Trick
df_Nat_Stat_Trick = pd.read_csv(os.path.join(path, 'Data', 'Original Data', 'NHL_Data_2008-2022_Nat_Stat_Trick.csv'), index_col = False,low_memory=False)

In [16]:
#import 'Schedule - Results_2008-2002_Hockey-Reference.csv' to make df_Results
df_Results = pd.read_csv(os.path.join(path, 'Data', 'Original Data', 'Schedule - Results_2008-2002_Hockey-Reference.csv'), index_col = False,low_memory=False)

# df_kaggle Check

In [19]:
#check head
df_kaggle.head(10)

,Team-Date Combined for Vlookup,team,season,name,gameId,playerTeam,opposingTeam,home_or_away,gameDate,position,...,unblockedShotAttemptsAgainst,scoreAdjustedUnblockedShotAttemptsAgainst,dZoneGiveawaysAgainst,xGoalsFromxReboundsOfShotsAgainst,xGoalsFromActualReboundsOfShotsAgainst,reboundxGoalsAgainst,totalShotCreditAgainst,scoreAdjustedTotalShotCreditAgainst,scoreFlurryAdjustedTotalShotCreditAgainst,playoffGame
0,NYR-20081004,NYR,2008,NYR,2008020001,NYR,TBL,AWAY,20081004,Team Level,...,31,30.369,5,0.396,0.168,0.168,2.917,2.833,2.714,0
1,NYR-20081004,NYR,2008,NYR,2008020001,NYR,TBL,AWAY,20081004,Team Level,...,20,19.369,3,0.237,0.168,0.168,1.862,1.777,1.665,0
2,NYR-20081005,NYR,2008,NYR,2008020003,NYR,TBL,HOME,20081005,Team Level,...,32,31.984,5,0.241,0.000,0.000,1.091,1.117,1.091,0
3,NYR-20081005,NYR,2008,NYR,2008020003,NYR,TBL,HOME,20081005,Team Level,...,23,22.984,4,0.170,0.000,0.000,0.973,0.998,0.973,0
4,NYR-20081010,NYR,2008,NYR,2008020010,NYR,CHI,HOME,20081010,Team Level,...,45,43.911,3,0.448,0.407,0.407,2.738,2.751,2.730,0
5,NYR-20081010,NYR,2008,NYR,2008020010,NYR,CHI,HOME,20081010,Team Level,...,38,36.911,3,0.356,0.407,0.407,2.408,2.421,2.400,0
6,NYR-20081011,NYR,2008,NYR,2008020019,NYR,PHI,AWAY,20081011,Team Level,...,41,38.025,4,0.504,0.401,0.401,3.123,2.958,2.907,0
7,NYR-20081011,NYR,2008,NYR,2008020019,NYR,PHI,AWAY,20081011,Team Level,...,28,25.025,4,0.273,0.401,0.401,1.624,1.459,1.437,0
8,NYR-20081013,NYR,2008,NYR,2008020034,NYR,NJD,HOME,20081013,Team Level,...,39,38.019,3,0.383,1.139,1.139,2.698,2.691,2.242,0
9,NYR-20081013,NYR,2008,NYR,2008020034,NYR,NJD,HOME,20081013,Team Level,...,28,27.019,3,0.245,1.139,1.139,0.934,0.927,0.916,0

In [20]:
df_kaggle.describe()

,season,gameId,gameDate,xGoalsPercentage,corsiPercentage,fenwickPercentage,iceTime,xOnGoalFor,xGoalsFor,xReboundsFor,...,unblockedShotAttemptsAgainst,scoreAdjustedUnblockedShotAttemptsAgainst,dZoneGiveawaysAgainst,xGoalsFromxReboundsOfShotsAgainst,xGoalsFromActualReboundsOfShotsAgainst,reboundxGoalsAgainst,totalShotCreditAgainst,scoreAdjustedTotalShotCreditAgainst,scoreFlurryAdjustedTotalShotCreditAgainst,playoffGame
count,70688.000000,7.068800e+04,7.068800e+04,70688.000000,70688.000000,70688.000000,70688.000000,70688.000000,70688.000000,70688.000000,...,70688.000000,70688.000000,70688.000000,70688.000000,70688.000000,70688.000000,70688.000000,70688.000000,70688.000000,70688.0
mean,2015.024106,2.015045e+09,2.015662e+07,0.500000,0.500000,0.500000,3280.163988,26.826011,2.340615,1.803895,...,37.463954,37.541303,4.591119,0.387008,0.411130,0.421704,2.300646,2.306743,2.261465,0.0
std,4.358500,4.358503e+06,4.398750e+04,0.115794,0.080811,0.083082,434.763948,6.924725,0.936659,0.537186,...,9.536742,9.509425,3.449006,0.125589,0.407038,0.410951,0.848722,0.854024,0.818562,0.0
min,2008.000000,2.008020e+09,2.008100e+07,0.084100,0.171400,0.155200,0.000000,0.000000,0.212000,0.000000,...,6.000000,5.962000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
25%,2011.000000,2.011021e+09,2.012012e+07,0.420100,0.444400,0.443200,2923.000000,21.961000,1.656000,1.421000,...,31.000000,30.746000,2.000000,0.296000,0.059000,0.076000,1.689000,1.695000,1.673000,0.0
50%,2015.000000,2.015021e+09,2.016016e+07,0.500000,0.500000,0.500000,3600.000000,26.456000,2.197000,1.756000,...,37.000000,37.008500,4.000000,0.372000,0.316000,0.326000,2.176000,2.179000,2.144000,0.0
75%,2019.000000,2.019020e+09,2.019102e+07,0.579900,0.555600,0.556800,3600.000000,31.293250,2.877000,2.139000,...,44.000000,43.777000,6.000000,0.464000,0.613000,0.626000,2.793000,2.798000,2.743000,0.0
max,2022.000000,2.022021e+09,2.023041e+07,0.915900,0.828600,0.844800,3900.000000,63.726000,11.565000,4.720000,...,88.000000,84.637000,30.000000,1.107000,4.067000,4.067000,11.234000,11.215000,8.304000,0.0

In [21]:
#check for missing values
df_kaggle.isnull().sum()

Team-Date Combined for Vlookup               0
team                                         0
season                                       0
name                                         0
gameId                                       0
                                            ..
reboundxGoalsAgainst                         0
totalShotCreditAgainst                       0
scoreAdjustedTotalShotCreditAgainst          0
scoreFlurryAdjustedTotalShotCreditAgainst    0
playoffGame                                  0
Length: 112, dtype: int64

In [27]:
# Check for duplicates
df_kaggle_dups = df_kaggle[df_kaggle.duplicated()]

In [28]:
df_kaggle_dups

Empty DataFrame
Columns: [Team-Date Combined for Vlookup, team, season, name, gameId, playerTeam, opposingTeam, home_or_away, gameDate, position, situation, xGoalsPercentage, corsiPercentage, fenwickPercentage, iceTime, xOnGoalFor, xGoalsFor, xReboundsFor, xFreezeFor, xPlayStoppedFor, xPlayContinuedInZoneFor, xPlayContinuedOutsideZoneFor, flurryAdjustedxGoalsFor, scoreVenueAdjustedxGoalsFor, flurryScoreVenueAdjustedxGoalsFor, shotsOnGoalFor, missedShotsFor, blockedShotAttemptsFor, shotAttemptsFor, goalsFor, reboundsFor, reboundGoalsFor, freezeFor, playStoppedFor, playContinuedInZoneFor, playContinuedOutsideZoneFor, savedShotsOnGoalFor, savedUnblockedShotAttemptsFor, penaltiesFor, penalityMinutesFor, faceOffsWonFor, hitsFor, takeawaysFor, giveawaysFor, lowDangerShotsFor, mediumDangerShotsFor, highDangerShotsFor, lowDangerxGoalsFor, mediumDangerxGoalsFor, highDangerxGoalsFor, lowDangerGoalsFor, mediumDangerGoalsFor, highDangerGoalsFor, scoreAdjustedShotsAttemptsFor, unblockedShotAttemptsFor, scoreAdjustedUnblockedShotAttemptsFor, dZoneGiveawaysFor, xGoalsFromxReboundsOfShotsFor, xGoalsFromActualReboundsOfShotsFor, reboundxGoalsFor, totalShotCreditFor, scoreAdjustedTotalShotCreditFor, scoreFlurryAdjustedTotalShotCreditFor, xOnGoalAgainst, xGoalsAgainst, xReboundsAgainst, xFreezeAgainst, xPlayStoppedAgainst, xPlayContinuedInZoneAgainst, xPlayContinuedOutsideZoneAgainst, flurryAdjustedxGoalsAgainst, scoreVenueAdjustedxGoalsAgainst, flurryScoreVenueAdjustedxGoalsAgainst, shotsOnGoalAgainst, missedShotsAgainst, blockedShotAttemptsAgainst, shotAttemptsAgainst, goalsAgainst, reboundsAgainst, reboundGoalsAgainst, freezeAgainst, playStoppedAgainst, playContinuedInZoneAgainst, playContinuedOutsideZoneAgainst, savedShotsOnGoalAgainst, savedUnblockedShotAttemptsAgainst, penaltiesAgainst, penalityMinutesAgainst, faceOffsWonAgainst, hitsAgainst, takeawaysAgainst, giveawaysAgainst, lowDangerShotsAgainst, mediumDangerShotsAgainst, highDangerShotsAgainst, lowDangerxGoalsAgainst, mediumDangerxGoalsAgainst, highDangerxGoalsAgainst, lowDangerGoalsAgainst, mediumDangerGoalsAgainst, ...]
Index: []

[0 rows x 112 columns]

# df_Nat_Stat_Trick Check

In [29]:
#check head
df_Nat_Stat_Trick.head(10)

,Team-Date Combined for Vlookup,Game (origional),Date,Year,Month,Day,Date Combined,matchup,Team,Abbreviation,...,LDGF,LDGA,LDGF%,LDSH%,LDSV%,SH%,SV%,PDO,Attendance,situation
0,NYR-20081004,"2008-10-04 - Rangers 2, Lightning 1",10/4/2008,2008,10,4,20081004,"Rangers 2, Lightning 1",New York Rangers,NYR,...,0,0,-,0,100,3.57,90.91,0.945,0,5on5
1,TBL-20081004,"2008-10-04 - Rangers 2, Lightning 1",10/4/2008,2008,10,4,20081004,"Rangers 2, Lightning 1",Tampa Bay Lightning,TBL,...,0,0,-,0,100,9.09,96.43,1.055,0,5on5
2,OTT-20081004,"2008-10-04 - Penguins 4, Senators 3",10/4/2008,2008,10,4,20081004,"Penguins 4, Senators 3",Ottawa Senators,OTT,...,0,0,-,0,100,4.55,88.24,0.928,0,5on5
3,PIT-20081004,"2008-10-04 - Penguins 4, Senators 3",10/4/2008,2008,10,4,20081004,"Penguins 4, Senators 3",Pittsburgh Penguins,PIT,...,0,0,-,0,100,11.76,95.45,1.072,0,5on5
4,NYR-20081005,"2008-10-05 - Lightning 1, Rangers 2",10/5/2008,2008,10,5,20081005,"Lightning 1, Rangers 2",New York Rangers,NYR,...,0,0,-,0,100,3.85,92.31,0.962,0,5on5
5,TBL-20081005,"2008-10-05 - Lightning 1, Rangers 2",10/5/2008,2008,10,5,20081005,"Lightning 1, Rangers 2",Tampa Bay Lightning,TBL,...,0,0,-,0,100,7.69,96.15,1.038,0,5on5
6,OTT-20081005,"2008-10-05 - Senators 3, Penguins 1",10/5/2008,2008,10,5,20081005,"Senators 3, Penguins 1",Ottawa Senators,OTT,...,0,0,-,0,100,7.14,100.00,1.071,0,5on5
7,PIT-20081005,"2008-10-05 - Senators 3, Penguins 1",10/5/2008,2008,10,5,20081005,"Senators 3, Penguins 1",Pittsburgh Penguins,PIT,...,0,0,-,0,100,0.00,92.86,0.929,0,5on5
8,DET-20081009,"2008-10-09 - Maple Leafs 3, Red Wings 2",10/9/2008,2008,10,9,20081009,"Maple Leafs 3, Red Wings 2",Detroit Red Wings,DET,...,0,0,-,0,100,3.23,92.00,0.952,0,5on5
9,TOR-20081009,"2008-10-09 - Maple Leafs 3, Red Wings 2",10/9/2008,2008,10,9,20081009,"Maple Leafs 3, Red Wings 2",Toronto Maple Leafs,TOR,...,0,0,-,0,100,8.00,96.77,1.048,0,5on5

In [30]:
df_Nat_Stat_Trick.describe()

,Year,Month,Day,Date Combined,TOI,CF,CA,CF%,FF,FA,...,LDCA,LDCF%,LDSF,LDSA,LDGF,LDGA,SH%,SV%,PDO,Attendance
count,70704.000000,70704.000000,70704.000000,7.070400e+04,70704.000000,70704.000000,70704.000000,70704.000000,70704.000000,70704.000000,...,70704.000000,70704.000000,70704.000000,70704.000000,70704.000000,70704.000000,70704.000000,70704.000000,70704.000000,70704.000000
mean,2015.598721,6.062344,15.383684,2.015661e+07,54.264520,50.015049,50.015049,50.000025,37.461077,37.461077,...,22.476776,50.000059,11.676086,11.676086,0.390558,0.390558,8.873097,91.127115,1.000005,15170.152580
std,4.405386,4.404349,8.740666,4.399544e+04,7.386737,12.355020,12.355020,8.081534,9.538522,9.538522,...,7.046589,10.492195,4.431038,4.431038,0.638331,0.638331,6.011025,6.011039,0.087746,6319.647326
min,2008.000000,1.000000,1.000000,2.008100e+07,26.533333,12.000000,12.000000,17.140000,7.000000,7.000000,...,3.000000,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000,50.000000,0.533000,0.000000
25%,2012.000000,2.000000,8.000000,2.012012e+07,47.966667,41.000000,41.000000,44.440000,31.000000,31.000000,...,17.000000,42.860000,9.000000,9.000000,0.000000,0.000000,4.350000,87.500000,0.941000,14443.000000
50%,2016.000000,4.000000,15.000000,2.016013e+07,60.000000,49.000000,49.000000,50.000000,37.000000,37.000000,...,22.000000,50.000000,11.000000,11.000000,0.000000,0.000000,8.110000,91.890000,1.000000,17562.000000
75%,2019.000000,11.000000,23.000000,2.019102e+07,60.000000,58.000000,58.000000,55.560000,44.000000,44.000000,...,27.000000,57.140000,14.000000,14.000000,1.000000,1.000000,12.500000,95.650000,1.059000,18651.000000
max,2023.000000,12.000000,31.000000,2.023041e+07,76.800000,116.000000,116.000000,82.860000,88.000000,88.000000,...,65.000000,90.000000,42.000000,42.000000,7.000000,7.000000,50.000000,100.000000,1.467000,105491.000000

In [31]:
#check for missing values
df_Nat_Stat_Trick.isnull().sum()

Team-Date Combined for Vlookup    0
Game (origional)                  0
Date                              0
Year                              0
Month                             0
                                 ..
SH%                               0
SV%                               0
PDO                               0
Attendance                        0
situation                         0
Length: 67, dtype: int64

In [32]:
# Check for duplicates
df_Nat_Stat_Trick_dups = df_Nat_Stat_Trick[df_Nat_Stat_Trick.duplicated()]

In [33]:
df_kaggle_dups

Empty DataFrame
Columns: [Team-Date Combined for Vlookup, team, season, name, gameId, playerTeam, opposingTeam, home_or_away, gameDate, position, situation, xGoalsPercentage, corsiPercentage, fenwickPercentage, iceTime, xOnGoalFor, xGoalsFor, xReboundsFor, xFreezeFor, xPlayStoppedFor, xPlayContinuedInZoneFor, xPlayContinuedOutsideZoneFor, flurryAdjustedxGoalsFor, scoreVenueAdjustedxGoalsFor, flurryScoreVenueAdjustedxGoalsFor, shotsOnGoalFor, missedShotsFor, blockedShotAttemptsFor, shotAttemptsFor, goalsFor, reboundsFor, reboundGoalsFor, freezeFor, playStoppedFor, playContinuedInZoneFor, playContinuedOutsideZoneFor, savedShotsOnGoalFor, savedUnblockedShotAttemptsFor, penaltiesFor, penalityMinutesFor, faceOffsWonFor, hitsFor, takeawaysFor, giveawaysFor, lowDangerShotsFor, mediumDangerShotsFor, highDangerShotsFor, lowDangerxGoalsFor, mediumDangerxGoalsFor, highDangerxGoalsFor, lowDangerGoalsFor, mediumDangerGoalsFor, highDangerGoalsFor, scoreAdjustedShotsAttemptsFor, unblockedShotAttemptsFor, scoreAdjustedUnblockedShotAttemptsFor, dZoneGiveawaysFor, xGoalsFromxReboundsOfShotsFor, xGoalsFromActualReboundsOfShotsFor, reboundxGoalsFor, totalShotCreditFor, scoreAdjustedTotalShotCreditFor, scoreFlurryAdjustedTotalShotCreditFor, xOnGoalAgainst, xGoalsAgainst, xReboundsAgainst, xFreezeAgainst, xPlayStoppedAgainst, xPlayContinuedInZoneAgainst, xPlayContinuedOutsideZoneAgainst, flurryAdjustedxGoalsAgainst, scoreVenueAdjustedxGoalsAgainst, flurryScoreVenueAdjustedxGoalsAgainst, shotsOnGoalAgainst, missedShotsAgainst, blockedShotAttemptsAgainst, shotAttemptsAgainst, goalsAgainst, reboundsAgainst, reboundGoalsAgainst, freezeAgainst, playStoppedAgainst, playContinuedInZoneAgainst, playContinuedOutsideZoneAgainst, savedShotsOnGoalAgainst, savedUnblockedShotAttemptsAgainst, penaltiesAgainst, penalityMinutesAgainst, faceOffsWonAgainst, hitsAgainst, takeawaysAgainst, giveawaysAgainst, lowDangerShotsAgainst, mediumDangerShotsAgainst, highDangerShotsAgainst, lowDangerxGoalsAgainst, mediumDangerxGoalsAgainst, highDangerxGoalsAgainst, lowDangerGoalsAgainst, mediumDangerGoalsAgainst, ...]
Index: []

[0 rows x 112 columns]

# df_Results Check

In [35]:
#check head
df_Results.head(10)

,Date,Year,Month,Day,Date Combined,Visitor,Abbreviation,Visitor-Team-Date Combined for Vlookup,G - Visitor,Home,Abbreviation.1,Home-Team-Date Combined for Vlookup,G - Home,OT,Att.,LOG,Notes
0,10/7/2022,2022,10,7,20221007,San Jose Sharks,SJS,SJS-20221007,1.0,Nashville Predators,NSH,NSH-20221007,4.0,NaN,16648.0,2:43,at (Prague CZ)
1,10/8/2022,2022,10,8,20221008,Nashville Predators,NSH,NSH-20221008,3.0,San Jose Sharks,SJS,SJS-20221008,2.0,NaN,17023.0,2:33,at (Prague CZ)
2,10/11/2022,2022,10,11,20221011,Vegas Golden Knights,VGK,VGK-20221011,4.0,Los Angeles Kings,LAK,LAK-20221011,3.0,NaN,18230.0,2:31,NaN
3,10/11/2022,2022,10,11,20221011,Tampa Bay Lightning,TBL,TBL-20221011,1.0,New York Rangers,NYR,NYR-20221011,3.0,NaN,18006.0,2:21,NaN
4,10/12/2022,2022,10,12,20221012,Seattle Kraken,SEA,SEA-20221012,4.0,Anaheim Ducks,ANA,ANA-20221012,5.0,OT,17530.0,2:28,NaN
5,10/12/2022,2022,10,12,20221012,Columbus Blue Jackets,CBJ,CBJ-20221012,1.0,Carolina Hurricanes,CAR,CAR-20221012,4.0,NaN,18824.0,2:37,NaN
6,10/12/2022,2022,10,12,20221012,Chicago Blackhawks,CHI,CHI-20221012,2.0,Colorado Avalanche,COL,COL-20221012,5.0,NaN,18143.0,2:19,NaN
7,10/12/2022,2022,10,12,20221012,Vancouver Canucks,VAN,VAN-20221012,3.0,Edmonton Oilers,EDM,EDM-20221012,5.0,NaN,18347.0,2:41,NaN
8,10/12/2022,2022,10,12,20221012,Toronto Maple Leafs,TOR,TOR-20221012,3.0,Montreal Canadiens,MTL,MTL-20221012,4.0,NaN,21105.0,2:30,NaN
9,10/12/2022,2022,10,12,20221012,Boston Bruins,BOS,BOS-20221012,5.0,Washington Capitals,WSH,WSH-20221012,2.0,NaN,18573.0,2:28,NaN

In [36]:
df_Results.describe()

,Year,Month,Day,Date Combined,G - Visitor,G - Home,Att.
count,17677.000000,17677.000000,17677.000000,1.767700e+04,17676.000000,17676.000000,17108.000000
mean,2015.598631,6.062058,15.384172,2.015661e+07,2.750905,3.022630,17052.429916
std,4.405371,4.404482,8.740844,4.399530e+04,1.625160,1.707409,3664.736562
min,2008.000000,1.000000,1.000000,2.008100e+07,0.000000,0.000000,100.000000
25%,2012.000000,2.000000,8.000000,2.012012e+07,2.000000,2.000000,16002.000000
50%,2016.000000,4.000000,15.000000,2.016013e+07,3.000000,3.000000,17850.000000
75%,2019.000000,11.000000,23.000000,2.019102e+07,4.000000,4.000000,18860.000000
max,2023.000000,12.000000,31.000000,2.023041e+07,10.000000,11.000000,105491.000000

In [37]:
#check for missing values
df_Results.isnull().sum()

Date                                          0
Year                                          0
Month                                         0
Day                                           0
Date Combined                                 0
Visitor                                       0
Abbreviation                                  0
Visitor-Team-Date Combined for Vlookup        0
G - Visitor                                   1
Home                                          0
Abbreviation.1                                0
Home-Team-Date Combined for Vlookup           0
G - Home                                      1
OT                                        13556
Att.                                        569
LOG                                        8102
Notes                                     17496
dtype: int64

In [38]:
# Check for duplicates
df_Results_dups = df_Results[df_Results.duplicated()]

In [39]:
df_Results_dups

Empty DataFrame
Columns: [Date, Year, Month, Day, Date Combined, Visitor, Abbreviation, Visitor-Team-Date Combined for Vlookup, G - Visitor, Home, Abbreviation.1, Home-Team-Date Combined for Vlookup, G - Home, OT, Att., LOG, Notes]
Index: []

# Export Clean Data

In [40]:
#Export df_kaggle
df_kaggle.to_csv(os.path.join(path, 'Data', 'Cleaned Data', 'kaggle_checked.csv'))

In [44]:
#Export df_Nat_Stat_Trick
df_Nat_Stat_Trick.to_csv(os.path.join(path, 'Data', 'Cleaned Data', 'Nat_Stat_Trick_checked.csv'))

In [45]:
#Export df_Results
df_Results.to_csv(os.path.join(path, 'Data', 'Cleaned Data', 'Results_checked.csv'))